# config.yaml
program: train_sim_v3.py
method: bayes
name: sweep
metric:
  goal: maximize
  name: val_acc
parameters:
  tv_weight: 
    # values: [0.0, 0.001, 0.002, 0.005, 0.01, 0.015, 0.02, 0.04, 0.05]
    min: 0.0000
    max: 0.01
  tv_train_weight:
    min: 0.0000
    max: 0.01

  