name: gaussian_splatting_v2
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.1.0
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-image
  - pillow
  - imageio
  - matplotlib
  - tqdm
  - pip
  - pip:
      - plyfile
      - opencv-python
      - tensorboard
      - -e ./submodules/diff-gaussian-rasterization
      - -e ./submodules/simple-knn

