wandb_version: 1

program:
  desc: null
  value: train_sim.py
method:
  desc: null
  value: bayes
name:
  desc: null
  value: sweep
metric:
  desc: null
  value:
    goal: maximize
    name: val_acc
parameters:
  desc: null
  value:
    tv_weight:
      min: 0.0
      max: 0.01
    tv_train_weight:
      min: 0.0
      max: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.18.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737343192
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.7.13
      5: 0.18.7
      8:
      - 5
      13: linux-x86_64
tv_train_weight:
  desc: null
  value: 0.0034363354786460577
tv_weight:
  desc: null
  value: 2.2376441846045924e-05
