# config.yaml
program: train_sim_multiviews.py
method: grid
name: run_n_train_images
parameters:
  tv_weight: 
    values: [0.0]
  tv_unseen_weight:
    values: [0.0]
  dls:
    values: [12, 20]
  resolution:
    values: [1]
  source_path:
    values: ["/home/wl757/multiplexed-pixels/plenoxels/blender_data/lego_gen12"]
  n_train_images:
    values: [1, 2, 3, 5, 10, 15, 20, 30, 40, 50]
  use_multiplexing:
    values:
      - true
      - false
command:
  - ${interpreter}
  - ${program}
  - --iterations
  - 3000
  - --output-id
  - 3
  - ${args_no_boolean_flags}
  