# config.yaml
program: train_sim_plain.py
method: grid
name: run_plain
parameters:
  tv_weight: 
    values: [0.0, 0.01, 1.0] # drop 0.01 for longer run
  tv_unseen_weight:
    values: [0.0, 0.01, 0.1] # drop (0) AND (0.01 or 0.1) for longer run
  dls:
    values: [14, 18, 22]
  resolution:
    values: [1, 2, 4, 8]
  source_path:
    values: ["/home/wl757/multiplexed-pixels/plenoxels/blender_data/chair",
             "/home/wl757/multiplexed-pixels/plenoxels/blender_data/drums",
             "/home/wl757/multiplexed-pixels/plenoxels/blender_data/materials",
             "/home/wl757/multiplexed-pixels/plenoxels/blender_data/mic",
             "/home/wl757/multiplexed-pixels/plenoxels/blender_data/ship",
             "/home/wl757/multiplexed-pixels/plenoxels/blender_data/ficus",
             "/home/wl757/multiplexed-pixels/plenoxels/blender_data/lego_gen12",
             "/home/wl757/multiplexed-pixels/plenoxels/blender_data/hotdog",]
command:
  - ${interpreter}
  - ${program}
  - --iterations
  - 3000
  - ${args}
  