wandb_version: 1

program:
  desc: null
  value: train_sim.py
method:
  desc: null
  value: grid
name:
  desc: null
  value: sweep
metric:
  desc: null
  value:
    goal: maximize
    name: val_acc
parameters:
  desc: null
  value:
    tv_weight:
      values:
      - 0.0
      - 0.001
      - 0.002
      - 0.005
      - 0.01
      - 0.015
      - 0.02
      - 0.04
      - 0.05
_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.18.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736321497
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.7.13
      5: 0.18.7
      8:
      - 5
      13: linux-x86_64
tv_weight:
  desc: null
  value: 0.001
